name: New taxon page panel
description: Open a new issue to describe and request a new taxon-page panel. 
title: "[Panel]: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: |
      A panel is a section in the taxon page.  This issue outlines and proposes a single new panel, its role, target audience, scope,
        and brief design [TODO: link to example]. As a way to provide transparency for what is being shown, a panel should address the statement "*As an X I need Y to answer question Q for audience A*".
      _Need help filling this out?  Once you have your panel details in hand, contact us and we'll help step you through filling out this issue._
- type: markdown
  attributes:
    value: |
      # Summary
      _To understand what you want, as a way to organize and prioritize what we build, please provide a summary in the following form._
- type: input 
  id: summary_x
  attributes:
    label: Your role 
    description: Who are you, i.e. in what role are you presenting this panel? 
    placeholder: Undergrad ecologist 
  validations:
    required: true 
- type: textarea
  id: summary_y
  attributes:
    label: Your needs
    description: What do you need to answer the questions that this panel addresses, a graph, table, map, text?
    placeholder: A table of data and corresponding bar-graph
  validations:
    required: true 
- type: textarea
  id: summary_q
  attributes:
    label: Audience question
    description: What is the question your _audience_ has that you seek to answer in this panel?
    placeholder:  What names were used for the species and its close relatives originally named Homo sapiens?
  validations:
    required: true 
- type: textarea
  id: summary_a
  attributes:
    label: Audience
    description: Who is your audience? Consider what expertise the person has prior to their engagement with this panel.  
    placeholder: e.g. Undergraduate, kindergarden child, farmer, taxonomists, policy writer, journalist
  validations:
    required: true 
- type: markdown
  attributes:
    value: |
      # Details
- type: markdown
  attributes:
    value: |
      ## Interface
- type: input 
  id: interface_title
  attributes:
    label: Header
    description: Suggested primary header (title of panel if present)
    placeholder: Type species 
  validations:
    required: true
- type: textarea 
  id: interface_napkin_sketch
  attributes:
    label: Napkin sketch 
    description: minimal visual description of panel, can add many iterations. 
    placeholder: Drag/drop your image here
  validations:
    required: false 
- type: textarea 
  id: interface_wireframe
  attributes:
    label: Wireframe 
    description: mocked digital description of the panel, can include screenshots
    placeholder: Drag/drop your image here
  validations:
    required: false 
- type: textarea 
  id: interface_actions
  attributes:
    label: Actions 
    description: What can the user do with this panel that is "unique" to this panel?  mocked digital description of the panel, can include screenshots.
    placeholder: Sort table by clicking column headers; filter to show records by year only. 
  validations:
    required: false 
- type: textarea 
  id: data 
  attributes:
    label: Data
    description: All panels will must have corresponding data-object that is accessible to the end user (e.g. by download of CSV, via JSON, GeoJSO, DwC Archive, etc.).  What does this look like?
    placeholder: A CSV file with the DwC headers specificEpithet, family, and year
  validations:
    required: true
- type: textarea 
  id: citation 
  attributes:
    label: Citation 
    description: What does a citation to the data look like for this section? 
    placeholder: Recommended.  TODO, provide example styles.
  validations:
    required: false 
- type: markdown
  attributes:
    value: | 
      ## Technical details
      _Largely completed by developers._
- type: textarea 
  id: technical_metadata 
  attributes:
    label: Metadata 
    description: What does a citation to the data look like for this section? 
    placeholder: |
      * General data source (e.g. TaxonWorks, ALA, GBIF, CoL, Globi)
      * API entry point or offline data-source?
      * Suitable for offline?
      * Suitable for print?
      * GH pages deployable?
      * Proximity map (What should be rendered close to this panel)
      * Dependent panels (minimize/eliminate these if possible)? (Reference by issue.)
      * Panel source code repository
  validations:
    required: false
