---
  header_logo_url: /images/logo.jpg
  header_logo_text: Orthoptera Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about

    - label: Recent
      link: /recent

    - label: Help
      link: /help
