# If you want to add any metadata not present here, you can do so by adding the prefix meta_
---
meta_keywords: "taxonpages, species, sfg, orthoptera, speciesfilegroup"
meta_description: "The Orthoptera Species File is a taxonomic database of the world's Orthoptera (grasshoppers, katydids, crickets, and related insects), both living and fossil."
meta_robots: "follow"
