---
  project_name: "Orthoptera Species File"
  project_citation: "Orthoptera Species File"
  project_url: "https://jlpereira.github.io/taxonpages_osf/"
  project_authors: "Cigliano, M.M., H. Braun, D.C. Eades & D. Otte."
