---
project_name: 'Orthoptera Species File'
project_citation: 'Orthoptera Species File'
project_url: 'http://orthoptera.speciesfile.org/'
project_authors: 'Cigliano, M.M., H. Braun, D.C. Eades & D. Otte.'
